### ISSUE TITLE
Colspan

### ISSUE THREAD

**Issue by tomdowning82** [jupitern/table#2]
Hi

Is there anyway of specify colspan across columns?

**Comment by jupitern** [comment]
Hi,
You can add attributes to any columns using method ->attr('colspan', '2', true)
The last param is a boolean to indicate weather to apply it to the table header (th) also.
```php
...
->column()
	->title('Name')
	->value('name')
	->attr('colspan', '2', true)	
->add()
...

**Comment by tomdowning82** [comment]
Great thanks! How about applying colspan on a thead > td?
Also, add 2 rows under thead?

(if possible!)

**Comment by tomdowning82** [comment]
Sorry I mean applying colspan to **thead only**, not tbody > td

**Comment by jupitern** [comment]
Sorry i misguided you.

to apply colspan to th
->attr('colspan', '2', true)

to apply colspan do td
->attr('colspan', '2')

this works with any other attribute or style.

I think that with the current release will not work with colspans because a th will be rendered for each column. I have submitted a change in dev-master to work with colspans. you will have to remove the title in other row using
->title(false)

can you please test and tell me if it's ok?

full example:
```php
\Jupitern\Table\Table::instance()
	->attr('id', 'demoTable')
	->attr('class', 'table table-bordered table-striped table-hover')
	->attr('cellspacing', '0')
	->setData([ [1, 'Peter', '35', '961 168 851'], [2, 'John', '44', '169 853 741'] ])
	->column()
		->title('Col 1')
		->value(0)
		->attr('colspan', "2", true)
	->add()
	->column()
		->title(false)
		->value(1)
	->add()
	->column()
		->title('Col 2')
		->value(2)
	->add()
	->column()
		->title('Col 3')
		->value(3)
	->add()
	->render();
